doctrine:
  dbal:
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        
        # Tables to be ignored by the schema tool
        schema_filter: ~^(?!(event_streams|projections|_))~
        
        profiling_collect_backtrace: '%kernel.debug%'
        
        ###> dama/doctrine-test-bundle
        # Starting from version 8 and only when using DBAL < 4
        # you need to make sure you have use_savepoints enabled for all relevant connections
        use_savepoints: true
        ###< dama/doctrine-test-bundle ###
      
      ecotone:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true
    mappings:
      Books:
        type: attribute
        dir: '%kernel.project_dir%/src/Catalog/Book/Infrastructure/Doctrine'
        prefix: 'App\Catalog\Book\Infrastructure\Doctrine'
        is_bundle: false
      Tags:
        type: attribute
        dir: '%kernel.project_dir%/src/Catalog/Tag/Infrastructure/Doctrine'
        prefix: 'App\Catalog\Tag\Infrastructure\Doctrine'
        is_bundle: false
    controller_resolver:
      auto_mapping: false

when@test:
  doctrine:
    dbal:
      connections:
        default:
          # "TEST_TOKEN" is typically set by ParaTest
          dbname_suffix: '_test%env(default::TEST_TOKEN)%'
        ecotone:
          dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
  
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
