@startuml overview
left to right direction

actor Customer
actor Admin

package "Bookshop System" {
    rectangle "Inventory Context" {
        usecase "Add New Book"
        usecase "Update Book Details"
        usecase "Remove Book"
        usecase "Manage Categories"
        usecase "Add New Stock"
        usecase "Check Stock"
        usecase "Book Out Of Stock" #lightyellow
        "Book Out Of Stock" .right.> "Check Stock" : <<extend>>
    }

    rectangle "Catalog Context" {
        usecase "Search Books"
        usecase "Search Books By Category"
        "Search Books By Category" -right-|> "Search Books"
    }

    rectangle "Order Context" {
        usecase "Purchase Book"
        usecase "View Order History"
    }

    rectangle "Payment Context" {
        usecase "Make Payment"
        usecase "Payment Error" #lightyellow
        "Payment Error" .right.> "Make Payment" : <<extend>>
    }
}

Admin --> "Add New Book"
Admin --> "Update Book Details"
Admin --> "Remove Book"
Admin --> "Add New Stock"
Admin --> "Manage Categories"

Customer --> "Search Books"

Customer --> "Purchase Book"
"Purchase Book" ..> "Check Stock" : <<include>>
"Purchase Book" ..> "Make Payment" : <<include>>
Customer --> "View Order History"
@enduml
