@startuml overview
left to right direction

actor Customer
actor Manager

package "Bookshop System" {
    rectangle Catalog {
        usecase "Add New Book"
        usecase "Update Book Details"
        usecase "Remove Book"
        usecase "Manage Categories"
        usecase "Add New Stock"
        usecase "Check Stock"
        usecase "Book Out Of Stock" #lightyellow
        usecase "Search Books"
        usecase "Search Books By Category"
        "Search Books By Category" -right-|> "Search Books"
        "Book Out Of Stock" .right.> "Check Stock" : <<extend>>
    }

    rectangle Orders {
        usecase "Purchase Book"
        usecase "View Order History"
    }

    rectangle Payments {
        usecase "Make Payment"
        usecase "Payment Error" #lightyellow
        "Payment Error" .right.> "Make Payment" : <<extend>>
    }
}

Manager --> "Add New Book"
Manager --> "Update Book Details"
Manager --> "Remove Book"
Manager --> "Add New Stock"
Manager --> "Manage Categories"

Customer --> "Search Books"

Customer --> "Purchase Book"
"Purchase Book" ..> "Check Stock" : <<include>>
"Purchase Book" ..> "Make Payment" : <<include>>
Customer --> "View Order History"
@enduml
