@startuml context_map
!include catalog_context.puml
!include orders_context.puml
!include payments_context.puml

Stock <..> Order : Stock updates
Order --> Book : Pricing data
Order ..> Payment : Order details
Payment ..> Order : Payment status
@enduml
